server:
  port: ${port:9001}
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.66.99:3306/leyou
    username: root
    password: root
  application:
    name: user-service
  main:
    banner-mode: 'off'
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.hatim: debug
test:
  name: 999
