server:
  port: ${port:9001}
# 配置eureka
eureka:
  client:
    service-url: # EurekaServer地址,多个地址以','隔开
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: user-service
  rabbitmq:
    host: 192.168.66.99
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.66.99:3306/leyou
    username: root
    password: root
  main:
    banner-mode: 'off'
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.hatim: debug
test:
  name: good service mmmm
